import React, { useEffect, useState } from 'react';
import { CheckCircle, Clock, FileText, XCircle } from 'lucide-react';
import StatisticsCard from '../components/StatisticsCard';
import ConfirmModal from '../components/ConfirmModal';
import api from '../services/api';

const AuthorityDashboard = () => {
  const [reports, setReports] = useState([]); const [stats, setStats] = useState({}); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [confirm, setConfirm] = useState(null);
  const load = async () => { try { const [reportRes, statsRes] = await Promise.all([api.get('/reports/operational'), api.get('/dashboard/statistics')]); setReports(reportRes.data.reports || []); setStats(statsRes.data.statistics || {}); } catch (err) { setError(err.response?.data?.message || 'Unable to load operational data.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const updateStatus = async () => { const { report, action } = confirm; try { await api.put(`/reports/operational/${report.id}/${action}`); setReports((items) => items.map((item) => item.id === report.id ? { ...item, status: action === 'verify' ? 'Verified' : 'Rejected' } : item)); setSuccess(`Report #${report.id} ${action === 'verify' ? 'verified' : 'rejected'}.`); } catch (err) { setError(err.response?.data?.message || 'Unable to update report status.'); } finally { setConfirm(null); } };
  const pending = reports.filter((report) => report.status === 'Pending'); const verified = reports.filter((report) => report.status === 'Verified');
  return <div className="main-content"><div className="mb-4"><h2>Authority Dashboard</h2><p className="text-muted">Review citizen hazard reports and coordinate the operational response.</p></div>{success && <div className="notice notice-success">{success}</div>}{error && <div className="notice notice-error">{error}</div>}<div className="grid-3 mb-4"><StatisticsCard title="Pending Reports" value={pending.length} icon={Clock} color="var(--color-warning)" /><StatisticsCard title="Verified Reports" value={verified.length} icon={CheckCircle} color="var(--color-success)" /><StatisticsCard title="Active Alerts" value={stats.activeAlerts || 0} icon={FileText} color="var(--color-primary)" /></div><div className="card"><h3>Pending Reports</h3>{loading ? <p>Loading reports...</p> : <div className="table-container"><table className="data-table"><thead><tr><th>Hazard</th><th>Location</th><th>Severity</th><th>Submitted by</th><th>Actions</th></tr></thead><tbody>{pending.map((report) => <tr key={report.id}><td>{report.aiAnalysis?.hazard_prediction || report.hazard_type}</td><td>{report.location}</td><td><span className={`badge badge-${report.severity.toLowerCase()}`}>{report.severity}</span></td><td>{report.user?.name || 'Citizen'}</td><td style={{ display: 'flex', gap: '0.5rem' }}><button className="btn btn-primary" onClick={() => setConfirm({ report, action: 'verify' })}>Verify</button><button className="btn btn-danger" onClick={() => setConfirm({ report, action: 'reject' })}>Reject</button></td></tr>)}{!pending.length && <tr><td colSpan="5" className="text-center">No pending reports.</td></tr>}</tbody></table></div>}</div><ConfirmModal isOpen={Boolean(confirm)} title={`${confirm?.action === 'verify' ? 'Verify' : 'Reject'} Report`} message={`Confirm ${confirm?.action || ''} for report #${confirm?.report?.id || ''}.`} confirmText={confirm?.action === 'verify' ? 'Verify' : 'Reject'} confirmVariant={confirm?.action === 'verify' ? 'success' : 'danger'} onConfirm={updateStatus} onCancel={() => setConfirm(null)} /></div>;
};
export default AuthorityDashboard;
