import React, { useEffect, useState } from 'react';
import { CheckCircle, XCircle } from 'lucide-react';
import ConfirmModal from '../components/ConfirmModal';
import api from '../services/api';

const PendingAuthorityApplications = () => {
  const [applications, setApplications] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [confirm, setConfirm] = useState(null);
  const load = async () => { try { setApplications((await api.get('/admin/pending-authorities')).data.authorities || []); } catch (err) { setError(err.response?.data?.message || 'Unable to load authority applications.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const decide = async () => { const { app, action } = confirm; try { await api.put(`/admin/${action}-authority/${app.id}`); setApplications((items) => items.filter((item) => item.id !== app.id)); setSuccess(`${app.name}'s application was ${action === 'approve' ? 'approved' : 'rejected'}.`); } catch (err) { setError(err.response?.data?.message || `Unable to ${action} application.`); } finally { setConfirm(null); } };
  return <div className="main-content"><h2>Pending Authority Applications</h2><p className="text-muted mb-3">Review official authority registrations before granting operational access.</p>{success && <div className="notice notice-success">{success}</div>}{error && <div className="notice notice-error">{error}</div>}{loading ? <p>Loading applications...</p> : <div className="table-container"><table className="data-table"><thead><tr><th>Name</th><th>Email</th><th>Department</th><th>Organization</th><th>Authority ID</th><th>Registered</th><th>Actions</th></tr></thead><tbody>{applications.map((app) => <tr key={app.id}><td>{app.name}</td><td>{app.email}</td><td>{app.department || '—'}</td><td>{app.organization || '—'}</td><td>{app.government_authority_id}</td><td>{new Date(app.registration_date).toLocaleDateString()}</td><td style={{ display: 'flex', gap: '0.5rem' }}><button className="btn btn-primary" onClick={() => setConfirm({ app, action: 'approve' })}><CheckCircle size={15} /> Approve</button><button className="btn btn-danger" onClick={() => setConfirm({ app, action: 'reject' })}><XCircle size={15} /> Reject</button></td></tr>)}{!applications.length && <tr><td colSpan="7" className="text-center">No pending applications.</td></tr>}</tbody></table></div>}<ConfirmModal isOpen={Boolean(confirm)} title={`${confirm?.action === 'approve' ? 'Approve' : 'Reject'} Authority Application`} message={`Confirm this decision for ${confirm?.app?.name || 'this applicant'}.`} confirmText={confirm?.action === 'approve' ? 'Approve' : 'Reject'} confirmVariant={confirm?.action === 'approve' ? 'success' : 'danger'} onConfirm={decide} onCancel={() => setConfirm(null)} /></div>;
};
export default PendingAuthorityApplications;
